#!/bin/bash

die () {
    echo >&2 "$@"
    exit 1
}

LOCATION="/usr/share/glacier-interface"
JAR="$LOCATION/glacier-interface.jar"

if [ ! -f $JAR ]; then
	die "The main application is not found, please reinstall"
fi

# Defaults
DEFAULT_CONFIG="$HOME/.gi.config.json"
EXTRAS=""

# Append config if the default base config file exist
if [ -r "$DEFAULT_CONFIG" ] && [[ ! "$@" == *"--config"* ]]; then
	EXTRAS="--config $DEFAULT_CONFIG"
fi

java -jar $JAR $EXTRAS $@

exit 0